[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.build]
cmds = [
  'composer install',
  'npm install',
  'npm run build',
  'cp .env.example .env',
  'php artisan key:generate',
  'php artisan migrate --force'
]

[phases.start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT}'
